modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "transporter"
version = "${version}"
displayName = "Transporter"
authors = "Lazurite Team"
description = "Beam model info to the server."
logoFile = "icon.png"

[[dependencies.transporter]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transporter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"